const ancestries_data = {
    anadi: {
        _id: "TQEqWqc7BYiadUdY",
        img: "systems/pf2e/icons/default-icons/alternatives/ancestries/anadi.svg",
        name: "Anadi",
        system: {
            additionalLanguages: {
                count: 0,
                custom: "",
                value: ["draconic", "elven", "fey", "gnoll", "iruxi", "orcish"],
            },
            boosts: {
                "0": { value: ["dex"] },
                "1": { value: ["wis"] },
                "2": { value: ["str", "dex", "con", "int", "wis", "cha"] },
            },
            description: {
                value:
                    "<p><em>Anadi people are reclusive, sapient spiders who hail from the jungles of southern Garund. Though they act in many ways like natural-born shapeshifters, their twin forms actually stem from carefully developed magic.</em></p>\n<p><em>@UUID[Compendium.pf2e.journals.JournalEntry.45SK8rdbbxvEHfMn.JournalEntryPage.9dpHTBpL3j8ZpqTS]{Anadi}</em></p>",
            },
            flaws: { "0": { value: ["con"] } },
            hp: 8,
            items: {
                cfaem: {
                    img: "systems/pf2e/icons/default-icons/feat.svg",
                    level: 1,
                    name: "Change Shape (Anadi)",
                    uuid: "Compendium.pf2e.ancestryfeatures.Item.Change Shape (Anadi)",
                },
                ctbld: {
                    img: "systems/pf2e/icons/default-icons/feat.svg",
                    level: 0,
                    name: "Fangs",
                    uuid: "Compendium.pf2e.ancestryfeatures.Item.Fangs",
                },
            },
            languages: { custom: "", value: ["anadi", "mwangi"] },
            publication: {
                license: "OGL",
                remaster: false,
                title: "Pathfinder Lost Omens: The Mwangi Expanse",
            },
            reach: 5,
            rules: [],
            size: "med",
            speed: 25,
            traits: { rarity: "rare", value: ["anadi", "humanoid"] },
            vision: "normal",
        },
        type: "ancestry",
    },
    android: {
        _id: "GfLwE884NoRC7cRi",
        img: "systems/pf2e/icons/default-icons/alternatives/ancestries/android.svg",
        name: "Android",
        system: {
            additionalLanguages: {
                count: 0,
                custom: "",
                value: [
                    "abyssal",
                    "celestial",
                    "draconic",
                    "dwarven",
                    "undercommon",
                    "utopian",
                ],
            },
            boosts: {
                "0": { value: ["dex"] },
                "1": { value: ["int"] },
                "2": { value: ["str", "dex", "con", "int", "wis", "cha"] },
            },
            description: {
                value:
                    "<p><em>Technological wonders from another world, androids have synthetic bodies and living </em><em>souls. Their dual nature makes them quick-thinking and calm under pressure, but </em><em>comfortable in stillness and solitude.</em></p>\n<p><em>@UUID[Compendium.pf2e.journals.JournalEntry.45SK8rdbbxvEHfMn.JournalEntryPage.dyusFHHyaQOaQhZ0]{Android}</em></p>",
            },
            flaws: { "0": { value: ["cha"] } },
            hp: 8,
            items: {
                fvpio: {
                    img: "systems/pf2e/icons/default-icons/feat.svg",
                    level: 1,
                    name: "Emotionally Unaware",
                    uuid: "Compendium.pf2e.ancestryfeatures.Item.Emotionally Unaware",
                },
                ouwoo: {
                    img: "systems/pf2e/icons/default-icons/feat.svg",
                    level: 1,
                    name: "Constructed",
                    uuid: "Compendium.pf2e.ancestryfeatures.Item.Constructed",
                },
            },
            languages: { custom: "", value: ["androffan", "common"] },
            publication: {
                license: "OGL",
                remaster: false,
                title: "Pathfinder Lost Omens: Ancestry Guide",
            },
            reach: 5,
            rules: [],
            size: "med",
            speed: 25,
            traits: { rarity: "rare", value: ["android", "humanoid"] },
            vision: "lowLightVision",
        },
        type: "ancestry",
    },
    automaton: {
        _id: "kYsBAJ103T44agJF",
        img: "systems/pf2e/icons/default-icons/alternatives/ancestries/automaton.svg",
        name: "Automaton",
        system: {
            additionalLanguages: {
                count: 0,
                custom: "",
                value: [
                    "abyssal",
                    "celestial",
                    "dwarven",
                    "elven",
                    "infernal",
                    "jistkan",
                    "petran",
                    "pyric",
                    "sussuran",
                    "thalassic",
                ],
            },
            boosts: {
                "0": { value: ["str"] },
                "1": { value: [] },
                "2": { value: ["str", "dex", "con", "int", "wis", "cha"] },
            },
            description: {
                value:
                    "<p><em>These intelligent constructs house actual souls and represent what remains of a dying empire's last attempt at greatness. Automatons combine technological ingenuity with magical power, creating a blended being wholly unique to Golarion.</em></p>\n<p>@UUID[Compendium.pf2e.journals.JournalEntry.45SK8rdbbxvEHfMn.JournalEntryPage.rsx8cRI20oEDgfQh]{Automaton}</p>",
            },
            flaws: { "0": { value: [] } },
            hp: 8,
            items: {
                l0mdk: {
                    img: "systems/pf2e/icons/default-icons/feat.svg",
                    level: 1,
                    name: "Constructed Body",
                    uuid: "Compendium.pf2e.ancestryfeatures.Item.Constructed Body",
                },
                l6cpr: {
                    img: "systems/pf2e/icons/default-icons/feat.svg",
                    level: 1,
                    name: "Automaton Core",
                    uuid: "Compendium.pf2e.ancestryfeatures.Item.Automaton Core",
                },
            },
            languages: { custom: "", value: ["common", "utopian"] },
            publication: {
                license: "OGL",
                remaster: false,
                title: "Pathfinder Guns & Gears",
            },
            reach: 5,
            rules: [
                {
                    choices: [
                        { label: "PF2E.ActorSizeMedium", value: "medium" },
                        { label: "PF2E.ActorSizeSmall", value: "small" },
                    ],
                    flag: "size",
                    key: "ChoiceSet",
                    prompt: "PF2E.SpecificRule.Prompt.CreatureSize",
                },
                {
                    key: "CreatureSize",
                    value: "{item|flags.pf2e.rulesSelections.size}",
                },
                {
                    key: "ActiveEffectLike",
                    mode: "override",
                    path: "flags.pf2e.automaton.enhancements",
                    priority: 10,
                    value: { greater: [], lesser: [] },
                },
            ],
            size: "med",
            speed: 25,
            traits: { rarity: "rare", value: ["automaton", "construct"] },
            vision: "lowLightVision",
        },
        type: "ancestry",
    },
    azarketi: {
        _id: "yFoojz6q3ZjvceFw",
        img: "systems/pf2e/icons/default-icons/alternatives/ancestries/azarketi.svg",
        name: "Azarketi",
        system: {
            additionalLanguages: {
                count: 0,
                custom: "",
                value: [
                    "aklo",
                    "azlanti",
                    "draconic",
                    "elven",
                    "thalassic",
                    "undercommon",
                ],
            },
            boosts: {
                "0": { value: ["cha"] },
                "1": { value: ["con"] },
                "2": { value: ["str", "dex", "con", "int", "wis", "cha"] },
            },
            description: {
                value:
                    "<p>Azarketis, inheritors of a shattered empire's legacy, hold their proud traditions close but still surface to interact with the rest of the world.</p>\n<p>The aquatic humanoids of the Inner Sea share a somber and burdened history. Most refer to these aquatic peoples as gillmen or sometimes Low Azlanti, though they typically refer to themselves as azarketi, an Azlanti word that translates roughly to “people of the seas.” After Earthfall, these proud humans were mutated into aquatic servants by their alghollthu foes. Feeling like they don't fully belong with their human brethren nor with the sea that binds them, many azarketis struggle for a sense of identity and purpose. Though they remain distrusted by the surface dwellers, azarketis celebrate their unique lineage and their descent from the venerated Azlanti culture.</p>\n<p>@UUID[Compendium.pf2e.journals.JournalEntry.45SK8rdbbxvEHfMn.JournalEntryPage.SNhp04cirQnnBTbb]{Azarketi}</p>",
            },
            flaws: { "0": { value: ["wis"] } },
            hp: 8,
            items: {
                mfgye: {
                    img: "systems/pf2e/icons/default-icons/feat.svg",
                    level: 1,
                    name: "Hydration",
                    uuid: "Compendium.pf2e.ancestryfeatures.Item.Hydration",
                },
                pvkub: {
                    img: "systems/pf2e/icons/default-icons/feat.svg",
                    level: 1,
                    name: "Swim",
                    uuid: "Compendium.pf2e.ancestryfeatures.Item.Swim",
                },
            },
            languages: { custom: "", value: ["alghollthu", "common"] },
            publication: {
                license: "OGL",
                remaster: false,
                title: "Pathfinder Lost Omens: Absalom, City of Lost Omens",
            },
            reach: 5,
            rules: [],
            size: "med",
            speed: 20,
            traits: {
                rarity: "uncommon",
                value: ["amphibious", "azarketi", "humanoid"],
            },
            vision: "lowLightVision",
        },
        type: "ancestry",
    },
    catfolk: {
        _id: "972EkpJOPv9KkQIW",
        img: "systems/pf2e/icons/default-icons/alternatives/ancestries/catfolk.svg",
        name: "Catfolk",
        system: {
            additionalLanguages: {
                count: 0,
                custom: "",
                value: [
                    "draconic",
                    "elven",
                    "fey",
                    "gnomish",
                    "goblin",
                    "halfling",
                    "iruxi",
                    "jotun",
                ],
            },
            boosts: {
                "0": { value: ["cha"] },
                "1": { value: ["dex"] },
                "2": { value: ["str", "dex", "con", "int", "wis", "cha"] },
            },
            description: {
                value:
                    "<p><em>Curious and gregarious wanderers, catfolk combine features of felines and humanoids in both appearance and temperament. They enjoy learning new things, collecting new tales and trinkets, and ensuring their loved ones are safe and happy. Catfolk view themselves as chosen guardians of natural places in the world and are often recklessly brave, even in the face of overwhelming opposition.</em></p>\n<p><em>@UUID[Compendium.pf2e.journals.JournalEntry.45SK8rdbbxvEHfMn.JournalEntryPage.5S1Pq3GoEzLfBbH7]{Catfolk}</em></p>",
            },
            flaws: { "0": { value: ["wis"] } },
            hp: 8,
            items: {
                iyksy: {
                    img: "systems/pf2e/icons/features/ancestry/land-on-your-feet.webp",
                    level: "1",
                    name: "Land on Your Feet",
                    uuid: "Compendium.pf2e.ancestryfeatures.Item.Land on Your Feet",
                },
            },
            languages: { custom: "", value: ["amurrun", "common"] },
            publication: {
                license: "OGL",
                remaster: false,
                title: "Pathfinder Advanced Player's Guide",
            },
            reach: 5,
            rules: [],
            size: "med",
            speed: 25,
            traits: { rarity: "uncommon", value: ["catfolk", "humanoid"] },
            vision: "lowLightVision",
        },
        type: "ancestry",
    },
    conrasu: {
        _id: "tZn4qIHCUA6wCdnI",
        img: "systems/pf2e/icons/default-icons/alternatives/ancestries/conrasu.svg",
        name: "Conrasu",
        system: {
            additionalLanguages: {
                count: 0,
                custom: "",
                value: ["celestial", "elven", "fey", "iruxi", "petran", "utopian"],
            },
            boosts: {
                "0": { value: ["con"] },
                "1": { value: ["wis"] },
                "2": { value: ["str", "dex", "con", "int", "wis", "cha"] },
            },
            description: {
                value:
                    "<p><em>Conrasus are shards of cosmic force given consciousness who construct intricate exoskeletons to interface with the mortal world. Both an integral part of the underlying processes of the universe and strangely set apart, conrasus look to aeons to understand their existence.</em></p>\n<p><em>@UUID[Compendium.pf2e.journals.JournalEntry.45SK8rdbbxvEHfMn.JournalEntryPage.ufWdokSN5W3Einus]{Conrasu}</em></p>",
            },
            flaws: { "0": { value: ["cha"] } },
            hp: 10,
            items: {
                tdik1: {
                    img: "systems/pf2e/icons/default-icons/feat.svg",
                    level: 1,
                    name: "Sunlight Healing",
                    uuid: "Compendium.pf2e.ancestryfeatures.Item.Sunlight Healing",
                },
            },
            languages: { custom: "", value: ["mwangi", "rasu"] },
            publication: {
                license: "OGL",
                remaster: false,
                title: "Pathfinder Lost Omens: The Mwangi Expanse",
            },
            reach: 5,
            rules: [
                {
                    category: "unarmed",
                    damage: { base: { damageType: "slashing", dice: 1, die: "d4" } },
                    group: "brawling",
                    img: "icons/commodities/claws/claw-bear-brown-grey.webp",
                    key: "Strike",
                    label: "PF2E.BattleForm.Attack.Claw",
                    predicate: ["evened-hand:claw"],
                    traits: ["agile", "finesse", "unarmed"],
                },
                {
                    category: "unarmed",
                    damage: { base: { damageType: "bludgeoning", dice: 1, die: "d6" } },
                    group: "brawling",
                    img: "systems/pf2e/icons/unarmed-attacks/branch.webp",
                    key: "Strike",
                    label: "PF2E.BattleForm.Attack.Branch",
                    predicate: ["evened-hand:branch"],
                    traits: ["backswing", "unarmed"],
                },
            ],
            size: "med",
            speed: 25,
            traits: { rarity: "rare", value: ["aeon", "conrasu", "plant"] },
            vision: "normal",
        },
        type: "ancestry",
    },
    dwarf: {
        _id: "BYj5ZvlXZdpaEgA6",
        img: "systems/pf2e/icons/default-icons/alternatives/ancestries/dwarf.svg",
        name: "Dwarf",
        system: {
            additionalLanguages: {
                count: 0,
                custom: "",
                value: ["gnomish", "goblin", "jotun", "orcish", "petran", "sakvroth"],
            },
            boosts: {
                "0": { value: ["con"] },
                "1": { value: ["wis"] },
                "2": { value: ["str", "dex", "con", "int", "wis", "cha"] },
            },
            description: {
                value:
                    "<p><em>Dwarves have a well-earned reputation as a stoic and stern people, ensconced within citadels and cities carved from solid rock. While some see them as dour and humorless crafters of stone and metal, dwarves and those who have spent time among them understand their unbridled zeal for their work, caring far more about quality than quantity. To a stranger, they can seem untrusting and clannish, but to their friends and family, they are warm and caring, their halls filled with the sounds of laughter and hammers hitting anvils.</em></p>\n<p><em>@UUID[Compendium.pf2e.journals.JournalEntry.45SK8rdbbxvEHfMn.JournalEntryPage.XzRv30zY3UXRbBho]{Dwarf}</em></p>",
            },
            flaws: { "0": { value: ["cha"] } },
            hp: 10,
            items: {
                "5vjeq": {
                    img: "systems/pf2e/icons/equipment/weapons/clan-dagger.webp",
                    level: 0,
                    name: "Clan Dagger",
                    uuid: "Compendium.pf2e.ancestryfeatures.Item.Clan Dagger",
                },
            },
            languages: { custom: "", value: ["common", "dwarven"] },
            publication: {
                license: "ORC",
                remaster: true,
                title: "Pathfinder Player Core",
            },
            reach: 5,
            rules: [],
            size: "med",
            speed: 20,
            traits: { rarity: "common", value: ["dwarf", "humanoid"] },
            vision: "darkvision",
        },
        type: "ancestry",
    },
    elf: {
        _id: "PgKmsA2aKdbLU6O0",
        img: "systems/pf2e/icons/default-icons/alternatives/ancestries/elf.svg",
        name: "Elf",
        system: {
            additionalLanguages: {
                count: 0,
                custom: "",
                value: [
                    "draconic",
                    "empyrean",
                    "fey",
                    "gnoll",
                    "gnomish",
                    "goblin",
                    "orcish",
                ],
            },
            boosts: {
                "0": { value: ["dex"] },
                "1": { value: ["int"] },
                "2": { value: ["str", "dex", "con", "int", "wis", "cha"] },
            },
            description: {
                value:
                    "<p><em>As an ancient people, elves have seen great change and have the perspective that can come only from watching the arc of history. After leaving the world in ancient times, they returned to a changed land, and they still struggle to reclaim their ancestral homes, most notably from terrible demons that have invaded parts of their lands. To some, the elves are objects of awe—graceful and beautiful, with immense talent and knowledge. Among themselves, however, the elves place far more importance on personal freedom than on living up to these ideals.</em></p>\n<p><em>@UUID[Compendium.pf2e.journals.JournalEntry.45SK8rdbbxvEHfMn.JournalEntryPage.3cfdiId1IoxLsF9V]{Elf}</em></p>",
            },
            flaws: { "0": { value: ["con"] } },
            hp: 6,
            items: {},
            languages: { custom: "", value: ["common", "elven"] },
            publication: {
                license: "ORC",
                remaster: true,
                title: "Pathfinder Player Core",
            },
            reach: 5,
            rules: [],
            size: "med",
            speed: 30,
            traits: { rarity: "common", value: ["elf", "humanoid"] },
            vision: "lowLightVision",
        },
        type: "ancestry",
    },
    fetchling: {
        _id: "hIA3qiUsxvLZXrFP",
        img: "systems/pf2e/icons/default-icons/alternatives/ancestries/fetchling.svg",
        name: "Fetchling",
        system: {
            additionalLanguages: {
                count: 0,
                custom: "",
                value: ["aklo", "draconic", "dziriak", "necril", "undercommon"],
            },
            boosts: {
                "0": { value: ["dex"] },
                "1": { value: [] },
                "2": { value: ["str", "dex", "con", "int", "wis", "cha"] },
            },
            description: {
                value:
                    "<p><em>Once human and now something apart, fetchlings display the Shadow Plane's ancient influence through monochrome complexions, glowing eyes, and the casting of supernatural shadows.</em></p>\n<p><em>@UUID[Compendium.pf2e.journals.JournalEntry.45SK8rdbbxvEHfMn.JournalEntryPage.RlMgeku1FNJjF7YR]{Fetchling}</em></p>",
            },
            flaws: { "0": { value: [] } },
            hp: 8,
            items: {},
            languages: { custom: "", value: ["common", "shadowtongue"] },
            publication: {
                license: "OGL",
                remaster: false,
                title: "Pathfinder Lost Omens: Ancestry Guide",
            },
            reach: 5,
            rules: [
                {
                    key: "ActiveEffectLike",
                    mode: "override",
                    path: "flags.pf2e.colorDarkvision",
                    value: true,
                },
            ],
            size: "med",
            speed: 25,
            traits: { rarity: "uncommon", value: ["fetchling", "humanoid"] },
            vision: "darkvision",
        },
        type: "ancestry",
    },
    fleshwarp: {
        _id: "FXlXmNBFiiz9oasi",
        img: "systems/pf2e/icons/default-icons/alternatives/ancestries/fleshwarp.svg",
        name: "Fleshwarp",
        system: {
            additionalLanguages: {
                count: 0,
                custom: "",
                value: [
                    "aklo",
                    "draconic",
                    "dwarven",
                    "elven",
                    "goblin",
                    "undercommon",
                ],
            },
            boosts: {
                "0": { value: ["con"] },
                "1": { value: [] },
                "2": { value: ["str", "dex", "con", "int", "wis", "cha"] },
            },
            description: {
                value:
                    "<p><em>Fleshwarps are people whose forms were created or radically transformed by magic, alchemy, or unnatural energies. Their unorthodox appearance can make it difficult for them to find a place for themselves in the world.</em></p>\n<p><em>@UUID[Compendium.pf2e.journals.JournalEntry.45SK8rdbbxvEHfMn.JournalEntryPage.vTB1bTYVE4onyyy1]{Fleshwarp}</em></p>",
            },
            flaws: { "0": { value: [] } },
            hp: 10,
            items: {
                "31xm9": {
                    img: "systems/pf2e/icons/default-icons/feat.svg",
                    level: 1,
                    name: "Unusual Anatomy",
                    uuid: "Compendium.pf2e.ancestryfeatures.Item.Unusual Anatomy",
                },
            },
            languages: { custom: "", value: ["common"] },
            publication: {
                license: "OGL",
                remaster: false,
                title: "Pathfinder Lost Omens: Ancestry Guide",
            },
            reach: 5,
            rules: [
                {
                    adjustName: false,
                    choices: [
                        { label: "PF2E.ActorSizeSmall", value: "sm" },
                        { label: "PF2E.ActorSizeMedium", value: "med" },
                    ],
                    flag: "fleshwarpSize",
                    key: "ChoiceSet",
                    prompt: "PF2E.SpecificRule.Prompt.CreatureSize",
                },
                {
                    key: "ActiveEffectLike",
                    mode: "override",
                    path: "system.traits.size.value",
                    value: "{item|flags.pf2e.rulesSelections.fleshwarpSize}",
                },
            ],
            size: "med",
            speed: 25,
            traits: { rarity: "rare", value: ["aberration", "humanoid"] },
            vision: "lowLightVision",
        },
        type: "ancestry",
    },
    ghoran: {
        _id: "tSurOqRcfumadTfr",
        img: "systems/pf2e/icons/default-icons/ancestry.svg",
        name: "Ghoran",
        system: {
            additionalLanguages: {
                count: 0,
                custom: "",
                value: ["aklo", "draconic", "elven", "gnomish", "jotun"],
            },
            boosts: {
                "0": { value: ["con"] },
                "1": { value: [] },
                "2": { value: ["str", "dex", "con", "int", "wis", "cha"] },
            },
            description: {
                value:
                    "<p>These intelligent plant people, created by a long-dead druid, possess a sort of immortality through their seeds—unless these are destroyed by external events other than merely the ravages of time.</p>\n<p>@UUID[Compendium.pf2e.journals.JournalEntry.45SK8rdbbxvEHfMn.JournalEntryPage.kRjkrWAqQNXj3LLP]{Ghoran}</p>",
            },
            flaws: { "0": { value: [] } },
            hp: 8,
            items: {
                Jpors: {
                    img: "icons/magic/nature/root-vine-beanstolk-green.webp",
                    level: 0,
                    name: "Photosynthesis",
                    uuid: "Compendium.pf2e.ancestryfeatures.Item.Photosynthesis",
                },
            },
            languages: { custom: "", value: ["common", "fey"] },
            publication: {
                license: "OGL",
                remaster: false,
                title: "Pathfinder Lost Omens: Impossible Lands",
            },
            reach: 5,
            rules: [],
            size: "med",
            speed: 25,
            traits: { rarity: "rare", value: ["ghoran", "humanoid", "plant"] },
            vision: "lowLightVision",
        },
        type: "ancestry",
    },
    gnoll: {
        _id: "vxbQ1Yw4qwgjTzqo",
        img: "systems/pf2e/icons/default-icons/alternatives/ancestries/gnoll.svg",
        name: "Gnoll",
        system: {
            additionalLanguages: {
                count: 0,
                custom: "",
                value: ["draconic", "elven", "fey", "iruxi", "necril", "orcish"],
            },
            boosts: {
                "0": { value: ["str"] },
                "1": { value: ["int"] },
                "2": { value: ["str", "dex", "con", "int", "wis", "cha"] },
            },
            description: {
                value:
                    "<p><em>Powerfully-built humanoids that resemble hyenas, gnolls are cunning warriors and hunters. Their frightening visage and efficient tactics have given them an ill-starred reputation.</em></p>\n<p><em>@UUID[Compendium.pf2e.journals.JournalEntry.45SK8rdbbxvEHfMn.JournalEntryPage.xBV8oGvecw7abZxc]{Gnoll}</em></p>",
            },
            flaws: { "0": { value: ["wis"] } },
            hp: 8,
            items: {
                r9df5: {
                    img: "systems/pf2e/icons/default-icons/feat.svg",
                    level: 1,
                    name: "Bite",
                    uuid: "Compendium.pf2e.ancestryfeatures.Item.Bite",
                },
            },
            languages: { custom: "", value: ["common", "gnoll"] },
            publication: {
                license: "OGL",
                remaster: false,
                title: "Pathfinder Lost Omens: The Mwangi Expanse",
            },
            reach: 5,
            rules: [],
            size: "med",
            speed: 25,
            traits: { rarity: "uncommon", value: ["gnoll", "humanoid"] },
            vision: "lowLightVision",
        },
        type: "ancestry",
    },
    gnome: {
        _id: "CYlfsYLJcBOgqKtD",
        img: "systems/pf2e/icons/default-icons/alternatives/ancestries/gnome.svg",
        name: "Gnome",
        system: {
            additionalLanguages: {
                count: 0,
                custom: "",
                value: ["draconic", "dwarven", "elven", "goblin", "jotun", "orcish"],
            },
            boosts: {
                "0": { value: ["cha"] },
                "1": { value: ["con"] },
                "2": { value: ["str", "dex", "con", "int", "wis", "cha"] },
            },
            description: {
                value:
                    "<p><em>Long ago, early gnome ancestors emigrated from the First World, realm of the fey. While it's unclear why the first gnomes wandered to Golarion, this lineage manifests in modern gnomes as bizarre reasoning, eccentricity, obsessive tendencies, and what some see as naivete. These qualities are further reflected in their physical characteristics, such as spindly limbs, brightly colored hair, and childlike and extremely expressive facial features that further reflect their otherworldly origins.</em></p>\n<p><em>@UUID[Compendium.pf2e.journals.JournalEntry.45SK8rdbbxvEHfMn.JournalEntryPage.qIu10HByKeRaPPvD]{Gnome}</em></p>",
            },
            flaws: { "0": { value: ["str"] } },
            hp: 8,
            items: {},
            languages: { custom: "", value: ["common", "gnomish", "fey"] },
            publication: {
                license: "ORC",
                remaster: true,
                title: "Pathfinder Player Core",
            },
            reach: 5,
            rules: [],
            size: "sm",
            speed: 25,
            traits: { rarity: "common", value: ["gnome", "humanoid"] },
            vision: "lowLightVision",
        },
        type: "ancestry",
    },
    goblin: {
        _id: "sQfjTMDaZbT9DThq",
        img: "systems/pf2e/icons/default-icons/alternatives/ancestries/goblin.svg",
        name: "Goblin",
        system: {
            additionalLanguages: {
                count: 0,
                custom: "",
                value: [
                    "draconic",
                    "dwarven",
                    "gnoll",
                    "gnomish",
                    "halfling",
                    "orcish",
                ],
            },
            boosts: {
                "0": { value: ["cha"] },
                "1": { value: ["dex"] },
                "2": { value: ["str", "dex", "con", "int", "wis", "cha"] },
            },
            description: {
                value:
                    "<p><em>The convoluted histories other people cling to don't interest goblins. These small folk live in the moment, and they prefer tall tales over factual records. The wars of a few decades ago might as well be from the ancient past. Misunderstood by other people, goblins are happy how they are. Goblin virtues are about being present, creative, and honest. They strive to lead fulfilled lives, rather than worrying about how their journeys will end. To tell stories, not nitpick the facts. To be small, but dream big.</em></p>\n<p><em>@UUID[Compendium.pf2e.journals.JournalEntry.45SK8rdbbxvEHfMn.JournalEntryPage.Gn0XGCWDb0N4zLE0]{Goblin}</em></p>",
            },
            flaws: { "0": { value: ["wis"] } },
            hp: 6,
            items: {},
            languages: { custom: "", value: ["common", "goblin"] },
            publication: {
                license: "OGL",
                remaster: false,
                title: "Pathfinder Core Rulebook",
            },
            reach: 5,
            rules: [],
            size: "sm",
            speed: 25,
            traits: { rarity: "common", value: ["goblin", "humanoid"] },
            vision: "darkvision",
        },
        type: "ancestry",
    },
    goloma: {
        _id: "c4secsSNG2AO7I5i",
        img: "systems/pf2e/icons/default-icons/alternatives/ancestries/goloma.svg",
        name: "Goloma",
        system: {
            additionalLanguages: {
                count: 0,
                custom: "",
                value: [
                    "abyssal",
                    "aklo",
                    "draconic",
                    "elven",
                    "fey",
                    "halfling",
                    "necril",
                    "orcish",
                ],
            },
            boosts: {
                "0": { value: ["wis"] },
                "1": { value: [] },
                "2": { value: ["str", "dex", "con", "int", "wis", "cha"] },
            },
            description: {
                value:
                    "<p><em>Golomas fear most other people and deliberately use their unusual biology to frighten off those they consider to be dangerous predators. Rarely seen and poorly understood, golomas' many-eyed and wooden faced visages instill terror in most they meet.</em></p>\n<p><em>@UUID[Compendium.pf2e.journals.JournalEntry.45SK8rdbbxvEHfMn.JournalEntryPage.jKglnHBFvzI80tIe]{Goloma}</em></p>",
            },
            flaws: { "0": { value: [] } },
            hp: 8,
            items: {
                "2lk67": {
                    img: "systems/pf2e/icons/default-icons/feat.svg",
                    level: 1,
                    name: "Eyes in Back",
                    uuid: "Compendium.pf2e.ancestryfeatures.Item.Eyes in Back",
                },
            },
            languages: { custom: "", value: ["goloma", "mwangi"] },
            publication: {
                license: "OGL",
                remaster: false,
                title: "Pathfinder Lost Omens: The Mwangi Expanse",
            },
            reach: 5,
            rules: [],
            size: "med",
            speed: 30,
            traits: { rarity: "rare", value: ["goloma", "humanoid"] },
            vision: "normal",
        },
        type: "ancestry",
    },
    grippli: {
        _id: "hXM5jXezIki1cMI2",
        img: "systems/pf2e/icons/default-icons/alternatives/ancestries/grippli.svg",
        name: "Grippli",
        system: {
            additionalLanguages: {
                count: 0,
                custom: "",
                value: [
                    "abyssal",
                    "boggard",
                    "draconic",
                    "elven",
                    "fey",
                    "iruxi",
                    "thalassic",
                ],
            },
            boosts: {
                "0": { value: ["dex"] },
                "1": { value: ["wis"] },
                "2": { value: ["str", "dex", "con", "int", "wis", "cha"] },
            },
            description: {
                value:
                    "<p><em>Gripplis are a shy and cautious people who generally seek to avoid being drawn into the complicated and dangerous affairs of others. Despite their outlook and small stature, gripplis often take bold and noble action when the situation demands it.</em></p>\n<p><em>@UUID[Compendium.pf2e.journals.JournalEntry.45SK8rdbbxvEHfMn.JournalEntryPage.FhIJtKcINEe7fipX]{Grippli}</em></p>",
            },
            flaws: { "0": { value: ["str"] } },
            hp: 6,
            items: {},
            languages: { custom: "", value: ["common", "grippli"] },
            publication: {
                license: "OGL",
                remaster: false,
                title: "Pathfinder Lost Omens: The Mwangi Expanse",
            },
            reach: 5,
            rules: [],
            size: "sm",
            speed: 25,
            traits: { rarity: "uncommon", value: ["grippli", "humanoid"] },
            vision: "lowLightVision",
        },
        type: "ancestry",
    },
    halfling: {
        _id: "GgZAHbrjnzWOZy2v",
        img: "systems/pf2e/icons/default-icons/alternatives/ancestries/halfling.svg",
        name: "Halfling",
        system: {
            additionalLanguages: {
                count: 0,
                custom: "",
                value: ["dwarven", "elven", "gnomish", "goblin"],
            },
            boosts: {
                "0": { value: ["dex"] },
                "1": { value: ["wis"] },
                "2": { value: ["str", "dex", "con", "int", "wis", "cha"] },
            },
            description: {
                value:
                    "<p><em>Claiming no place as their own, halflings control few settlements larger than villages. Instead, they frequently live among humans within the walls of larger cities, carving out small communities alongside taller folk. Many halflings lead perfectly fulfilling lives in the shadows of their larger neighbors, while others prefer a nomadic existence, traveling the world and taking advantage of opportunities and adventures as they come.</em></p>\n<p><em>@UUID[Compendium.pf2e.journals.JournalEntry.45SK8rdbbxvEHfMn.JournalEntryPage.voI7uPS9vsG74JIn]{Halfling}</em></p>",
            },
            flaws: { "0": { value: ["str"] } },
            hp: 6,
            items: {
                "3084v": {
                    img: "systems/pf2e/icons/features/ancestry/keen-eyes.webp",
                    level: "0",
                    name: "Keen Eyes",
                    uuid: "Compendium.pf2e.ancestryfeatures.Item.Keen Eyes",
                },
            },
            languages: { custom: "", value: ["common", "halfling"] },
            publication: {
                license: "OGL",
                remaster: false,
                title: "Pathfinder Core Rulebook",
            },
            reach: 5,
            rules: [],
            size: "sm",
            speed: 25,
            traits: { rarity: "common", value: ["halfling", "humanoid"] },
            vision: "normal",
        },
        type: "ancestry",
    },
    hobgoblin: {
        _id: "piNLXUrm9iaGqD2i",
        img: "systems/pf2e/icons/default-icons/alternatives/ancestries/hobgoblin.svg",
        name: "Hobgoblin",
        system: {
            additionalLanguages: {
                count: 0,
                custom: "",
                value: ["draconic", "dwarven", "gnoll", "halfling", "jotun", "orcish"],
            },
            boosts: {
                "0": { value: ["con"] },
                "1": { value: ["int"] },
                "2": { value: ["str", "dex", "con", "int", "wis", "cha"] },
            },
            description: {
                value:
                    "<p><em>Taller and stronger than their goblin kin, hobgoblins are equals in strength and size to humans, with broad shoulders and long, powerful arms.</em></p>\n<p><em>@UUID[Compendium.pf2e.journals.JournalEntry.45SK8rdbbxvEHfMn.JournalEntryPage.DuWzeY4zugKFFthl]{Hobgoblin}</em></p>",
            },
            flaws: { "0": { value: ["wis"] } },
            hp: 8,
            items: {},
            languages: { custom: "", value: ["common", "goblin"] },
            publication: {
                license: "OGL",
                remaster: false,
                title: "Pathfinder Lost Omens: Character Guide",
            },
            reach: 5,
            rules: [],
            size: "med",
            speed: 25,
            traits: { rarity: "uncommon", value: ["goblin", "humanoid"] },
            vision: "darkvision",
        },
        type: "ancestry",
    },
    human: {
        _id: "IiG7DgeLWYrSNXuX",
        img: "systems/pf2e/icons/default-icons/alternatives/ancestries/human.svg",
        name: "Human",
        system: {
            additionalLanguages: { count: 1, custom: "", value: [] },
            boosts: {
                "0": { value: ["cha", "con", "dex", "int", "str", "wis"] },
                "1": { value: ["str", "dex", "con", "int", "wis", "cha"] },
                "2": { value: [] },
            },
            description: {
                value:
                    "<p><em>As unpredictable and varied as any of Golarion's peoples, humans have exceptional drive and the capacity to endure and expand. Though many civilizations thrived before humanity rose to prominence, humans have built some of the greatest and the most terrible societies throughout the course of history, and today they are the most populous people in the realms around the Inner Sea.</em></p>\n<p><em>@UUID[Compendium.pf2e.journals.JournalEntry.45SK8rdbbxvEHfMn.JournalEntryPage.7pU8yM7yPMw92SY3]{Human}</em></p>",
            },
            flaws: { "0": { value: [] } },
            hp: 8,
            items: {},
            languages: { custom: "", value: ["common"] },
            publication: {
                license: "OGL",
                remaster: false,
                title: "Pathfinder Core Rulebook",
            },
            reach: 5,
            rules: [],
            size: "med",
            speed: 25,
            traits: { rarity: "common", value: ["human", "humanoid"] },
            vision: "normal",
        },
        type: "ancestry",
    },
    kashrishi: {
        _id: "dw2K1AJR9mQ25nDP",
        img: "systems/pf2e/icons/default-icons/alternatives/ancestries/kashrishi.svg",
        name: "Kashrishi",
        system: {
            additionalLanguages: {
                count: 0,
                custom: "",
                value: ["celestial", "draconic", "fey", "petran", "thalassic"],
            },
            boosts: {
                "0": { value: ["con"] },
                "1": { value: [] },
                "2": { value: ["str", "dex", "con", "int", "wis", "cha"] },
            },
            description: {
                value:
                    "<p>Kashrishi make their homes in remote areas of the world. These quiet beings have stout, durable frames and distinctive crystalline horns. Their inherent psychic abilities make them natural empaths but also occasionally burden them with the unceasing thoughts of their neighbors.</p>\n<p>@UUID[Compendium.pf2e.journals.JournalEntry.45SK8rdbbxvEHfMn.JournalEntryPage.IJOH7nk0w1IybAhp]{Kashrishi}</p>",
            },
            flaws: { "0": { value: [] } },
            hp: 8,
            items: {
                iaCUe: {
                    img: "systems/pf2e/icons/spells/enthrall.webp",
                    level: 0,
                    name: "Empathic Sense",
                    uuid: "Compendium.pf2e.ancestryfeatures.Item.Empathic Sense",
                },
                wceqv: {
                    img: "systems/pf2e/icons/spells/searing-light.webp",
                    level: 0,
                    name: "Glowing Horn",
                    uuid: "Compendium.pf2e.ancestryfeatures.Item.Glowing Horn",
                },
            },
            languages: { custom: "", value: ["common"] },
            publication: {
                license: "OGL",
                remaster: false,
                title: "Pathfinder Lost Omens: Impossible Lands",
            },
            reach: 5,
            rules: [],
            size: "sm",
            speed: 25,
            traits: { rarity: "rare", value: ["humanoid", "kashrishi"] },
            vision: "normal",
        },
        type: "ancestry",
    },
    kitsune: {
        _id: "4BL5wf1VF9feC2rY",
        img: "systems/pf2e/icons/default-icons/alternatives/ancestries/kitsune.svg",
        name: "Kitsune",
        system: {
            additionalLanguages: {
                count: 0,
                custom: "",
                value: ["dwarven", "elven", "fey", "gnomish", "goblin", "halfling"],
            },
            boosts: {
                "0": { value: ["cha"] },
                "1": { value: [] },
                "2": { value: ["str", "dex", "con", "int", "wis", "cha"] },
            },
            description: {
                value:
                    "<p><em>Kitsune are a charismatic and witty people with a connection to the spiritual that grants them many magical abilities, chiefly the power to shapechange into other forms. Whether they pass unseen among other peoples or hold their tails high, kitsune are clever observers of the societies around them.</em></p>\n<p>@UUID[Compendium.pf2e.journals.JournalEntry.45SK8rdbbxvEHfMn.JournalEntryPage.26YL1jOPQQS6k7A9]{Kitsune}</p>",
            },
            flaws: { "0": { value: [] } },
            hp: 8,
            items: {
                "7ytru": {
                    img: "systems/pf2e/icons/default-icons/feat.svg",
                    level: 1,
                    name: "Change Shape",
                    uuid: "Compendium.pf2e.ancestryfeatures.Item.Change Shape (Kitsune)",
                },
            },
            languages: { custom: "", value: ["common"] },
            publication: {
                license: "OGL",
                remaster: false,
                title: "Pathfinder Lost Omens: Ancestry Guide",
            },
            reach: 5,
            rules: [],
            size: "med",
            speed: 25,
            traits: { rarity: "uncommon", value: ["humanoid", "kitsune"] },
            vision: "lowLightVision",
        },
        type: "ancestry",
    },
    kobold: {
        _id: "7oQxL6wgsokD3QXG",
        img: "systems/pf2e/icons/default-icons/alternatives/ancestries/kobold.svg",
        name: "Kobold",
        system: {
            additionalLanguages: {
                count: 0,
                custom: "",
                value: [
                    "aklo",
                    "dwarven",
                    "gnomish",
                    "infernal",
                    "petran",
                    "undercommon",
                ],
            },
            boosts: {
                "0": { value: ["cha"] },
                "1": { value: ["dex"] },
                "2": { value: ["str", "dex", "con", "int", "wis", "cha"] },
            },
            description: {
                value:
                    "<p><em>Every kobold knows that their slight frame belies true, mighty draconic power. They are ingenious crafters and devoted allies within their warrens, but those who trespass into their territory find them to be inspired skirmishers, especially when they have the backing of a draconic sorcerer or true dragon overlord. However, these reptilian opportunists prove happy to cooperate with other humanoids when it's to their benefit, combining caution and cunning to make their fortunes in the wider world.</em></p>\n<p><em>@UUID[Compendium.pf2e.journals.JournalEntry.45SK8rdbbxvEHfMn.JournalEntryPage.naQrTTE7CXu5lnNt]{Kobold}</em></p>",
            },
            flaws: { "0": { value: ["con"] } },
            hp: 6,
            items: {
                xhq7h: {
                    img: "systems/pf2e/icons/features/ancestry/draconic-exemplar.webp",
                    level: "1",
                    name: "Draconic Exemplar",
                    uuid: "Compendium.pf2e.ancestryfeatures.Item.Draconic Exemplar",
                },
            },
            languages: { custom: "", value: ["common", "draconic"] },
            publication: {
                license: "OGL",
                remaster: false,
                title: "Pathfinder Advanced Player's Guide",
            },
            reach: 5,
            rules: [],
            size: "sm",
            speed: 25,
            traits: { rarity: "uncommon", value: ["humanoid", "kobold"] },
            vision: "darkvision",
        },
        type: "ancestry",
    },
    leshy: {
        _id: "cdhgByGG1WtuaK73",
        img: "systems/pf2e/icons/default-icons/alternatives/ancestries/leshy.svg",
        name: "Leshy",
        system: {
            additionalLanguages: {
                count: 0,
                custom: "",
                value: [
                    "draconic",
                    "elven",
                    "gnomish",
                    "goblin",
                    "halfling",
                    "sakvroth",
                ],
            },
            boosts: {
                "0": { value: ["con"] },
                "1": { value: ["wis"] },
                "2": { value: ["str", "dex", "con", "int", "wis", "cha"] },
            },
            description: {
                value:
                    "<p><em>Guardians and emissaries of the environment, leshies are immortal spirits of nature temporarily granted a physical form.</em></p>\n<p><em>@UUID[Compendium.pf2e.journals.JournalEntry.45SK8rdbbxvEHfMn.JournalEntryPage.SWkwNivrfzWZqas9]{Leshy}</em></p>",
            },
            flaws: { "0": { value: ["int"] } },
            hp: 8,
            items: {
                "32oz7": {
                    img: "icons/magic/nature/root-vine-beanstolk-green.webp",
                    level: "1",
                    name: "Plant Nourishment",
                    uuid: "Compendium.pf2e.ancestryfeatures.Item.Plant Nourishment",
                },
            },
            languages: { custom: "", value: ["common", "fey"] },
            publication: {
                license: "ORC",
                remaster: true,
                title: "Pathfinder Player Core",
            },
            reach: 5,
            rules: [],
            size: "sm",
            speed: 25,
            traits: { rarity: "common", value: ["leshy", "plant"] },
            vision: "lowLightVision",
        },
        type: "ancestry",
    },
    lizardfolk: {
        _id: "HWEgF7Gmoq55VhTL",
        img: "systems/pf2e/icons/default-icons/alternatives/ancestries/lizardfolk.svg",
        name: "Lizardfolk",
        system: {
            additionalLanguages: {
                count: 0,
                custom: "",
                value: [
                    "amurrun",
                    "boggard",
                    "draconic",
                    "elven",
                    "fey",
                    "jotun",
                    "thalassic",
                ],
            },
            boosts: {
                "0": { value: ["str"] },
                "1": { value: ["wis"] },
                "2": { value: ["str", "dex", "con", "int", "wis", "cha"] },
            },
            description: {
                value:
                    "<p><em>Lizardfolk are consummate survivors, heirs to empires considered ancient even by the elves.</em></p>\n<p><em>@UUID[Compendium.pf2e.journals.JournalEntry.45SK8rdbbxvEHfMn.JournalEntryPage.cbLJs37Nc8FveriK]{Lizardfolk}</em></p>",
            },
            flaws: { "0": { value: ["int"] } },
            hp: 8,
            items: {
                ry9ai: {
                    img: "systems/pf2e/icons/features/ancestry//aquatic-adaptation.webp",
                    level: "1",
                    name: "Aquatic Adaptation",
                    uuid: "Compendium.pf2e.ancestryfeatures.Item.Aquatic Adaptation",
                },
                xkzsg: {
                    img: "systems/pf2e/icons/features/ancestry/claws.webp",
                    level: "1",
                    name: "Claws",
                    uuid: "Compendium.pf2e.ancestryfeatures.Item.Claws",
                },
            },
            languages: { custom: "", value: ["common", "iruxi"] },
            publication: {
                license: "OGL",
                remaster: false,
                title: "Pathfinder Lost Omens: Character Guide",
            },
            reach: 5,
            rules: [],
            size: "med",
            speed: 25,
            traits: { rarity: "uncommon", value: ["humanoid", "lizardfolk"] },
            vision: "normal",
        },
        type: "ancestry",
    },
    nagaji: {
        _id: "J7T7bDLaQGoY1sMF",
        img: "systems/pf2e/icons/default-icons/ancestry.svg",
        name: "Nagaji",
        system: {
            additionalLanguages: {
                count: 0,
                custom: "",
                value: [
                    "aklo",
                    "amurrun",
                    "celestial",
                    "draconic",
                    "shadowtongue",
                    "tengu",
                    "thalassic",
                    "undercommon",
                    "vanara",
                ],
            },
            boosts: {
                "0": { value: ["str"] },
                "1": { value: [] },
                "2": { value: ["str", "dex", "con", "int", "wis", "cha"] },
            },
            description: {
                value:
                    "<p>With humanoid figures and serpentine heads, nagaji are heralds, companions, and servitors of powerful nagas. They hold a deep reverence for holy areas and spiritual truths, an aspect many others find as intimidating as a nagaji's appearance.</p>\n<p>@UUID[Compendium.pf2e.journals.JournalEntry.45SK8rdbbxvEHfMn.JournalEntryPage.TlTIwW61zK0dk95v]{Nagaji}</p>",
            },
            flaws: { "0": { value: [] } },
            hp: 10,
            items: {
                O6GUQ: {
                    img: "systems/pf2e/icons/unarmed-attacks/fangs.webp",
                    level: 0,
                    name: "Fangs (Nagaji)",
                    uuid: "Compendium.pf2e.ancestryfeatures.Item.Fangs (Nagaji)",
                },
            },
            languages: { custom: "", value: ["common", "nagaji"] },
            publication: {
                license: "OGL",
                remaster: false,
                title: "Pathfinder Lost Omens: Impossible Lands",
            },
            reach: 5,
            rules: [],
            size: "med",
            speed: 25,
            traits: { rarity: "uncommon", value: ["humanoid", "nagaji"] },
            vision: "lowLightVision",
        },
        type: "ancestry",
    },
    orc: {
        _id: "lSGWXjcbOa6O5fTx",
        img: "systems/pf2e/icons/default-icons/alternatives/ancestries/orc.svg",
        name: "Orc",
        system: {
            additionalLanguages: {
                count: 0,
                custom: "",
                value: ["goblin", "jotun", "petran", "sakvroth"],
            },
            boosts: {
                "0": { value: ["cha", "con", "dex", "int", "str", "wis"] },
                "1": { value: ["cha", "con", "dex", "int", "str", "wis"] },
                "2": { value: [] },
            },
            description: {
                value:
                    "<p><em>Orcs are forged in the fires of violence and conflict, often from the moment they are born. As they live lives that are frequently cut brutally short, orcs revel in testing their strength against worthy foes, whether by challenging a higher-ranking member of their community for dominance or raiding a neighboring settlement. Many orcs seek glory as soon as they can walk and carry a blade or club, taming wild beasts or hunting deadly monsters.</em></p>\n<p><em>@UUID[Compendium.pf2e.journals.JournalEntry.45SK8rdbbxvEHfMn.JournalEntryPage.GCxhDyf1ZNlLiDKZ]{Orc}</em></p>",
            },
            flaws: { "0": { value: [] } },
            hp: 10,
            items: {},
            languages: { custom: "", value: ["common", "orcish"] },
            publication: {
                license: "ORC",
                remaster: true,
                title: "Pathfinder Player Core",
            },
            reach: 5,
            rules: [],
            size: "med",
            speed: 25,
            traits: { rarity: "common", value: ["humanoid", "orc"] },
            vision: "darkvision",
        },
        type: "ancestry",
    },
    poppet: {
        _id: "6F2fSFC1Eo1JdpY4",
        img: "systems/pf2e/icons/default-icons/alternatives/ancestries/poppet.svg",
        name: "Poppet",
        system: {
            additionalLanguages: {
                count: 0,
                custom: "",
                value: ["draconic", "dwarven", "elven", "fey", "gnomish", "goblin"],
            },
            boosts: {
                "0": { value: ["con"] },
                "1": { value: ["cha"] },
                "2": { value: ["str", "dex", "con", "int", "wis", "cha"] },
            },
            description: {
                value:
                    "<p><em>Poppets are small, basic constructs that typically help their owners with simple tasks. Occasionally, poppets gain sapience, independence, and a spark of life. Elevated beyond mere helpers or playthings, these poppets are free to chart their own destinies.</em></p>\n<p><em>@UUID[Compendium.pf2e.journals.JournalEntry.45SK8rdbbxvEHfMn.JournalEntryPage.Ck8L9livQph1GFal]{Poppet}</em></p>",
            },
            flaws: { "0": { value: ["dex"] } },
            hp: 6,
            items: {
                "3fzmc": {
                    img: "systems/pf2e/icons/default-icons/feat.svg",
                    level: 1,
                    name: "Constructed (Poppet)",
                    uuid: "Compendium.pf2e.ancestryfeatures.Item.Constructed (Poppet)",
                },
                giqow: {
                    img: "systems/pf2e/icons/default-icons/feat.svg",
                    level: 1,
                    name: "Flammable",
                    uuid: "Compendium.pf2e.ancestryfeatures.Item.Flammable",
                },
            },
            languages: { custom: "", value: ["common"] },
            publication: {
                license: "OGL",
                remaster: false,
                title: "Pathfinder Lost Omens: The Grand Bazaar",
            },
            reach: 5,
            rules: [],
            size: "sm",
            speed: 25,
            traits: { rarity: "rare", value: ["construct", "humanoid"] },
            vision: "darkvision",
        },
        type: "ancestry",
    },
    ratfolk: {
        _id: "P6PcVnCkh4XMdefw",
        img: "systems/pf2e/icons/default-icons/alternatives/ancestries/ratfolk.svg",
        name: "Ratfolk",
        system: {
            additionalLanguages: {
                count: 0,
                custom: "",
                value: [
                    "aklo",
                    "draconic",
                    "dwarven",
                    "gnoll",
                    "gnomish",
                    "goblin",
                    "halfling",
                    "orcish",
                    "undercommon",
                ],
            },
            boosts: {
                "0": { value: ["dex"] },
                "1": { value: ["int"] },
                "2": { value: ["str", "dex", "con", "int", "wis", "cha"] },
            },
            description: {
                value:
                    "<p><em>Ysoki—as ratfolk call themselves—are a clever, adaptable, and fastidious ancestry who happily crowd their large families into the smallest of living spaces.</em></p>\n<p><em>@UUID[Compendium.pf2e.journals.JournalEntry.45SK8rdbbxvEHfMn.JournalEntryPage.zoSkNev57C8OEDYL]{Ratfolk}</em></p>",
            },
            flaws: { "0": { value: ["str"] } },
            hp: 6,
            items: {},
            languages: { custom: "", value: ["common", "ysoki"] },
            publication: {
                license: "OGL",
                remaster: false,
                title: "Pathfinder Advanced Player's Guide",
            },
            reach: 5,
            rules: [],
            size: "sm",
            speed: 25,
            traits: { rarity: "uncommon", value: ["humanoid", "ratfolk"] },
            vision: "lowLightVision",
        },
        type: "ancestry",
    },
    shisk: {
        _id: "x1YinOddgUxwOLqP",
        img: "systems/pf2e/icons/default-icons/alternatives/ancestries/shisk.svg",
        name: "Shisk",
        system: {
            additionalLanguages: {
                count: 0,
                custom: "",
                value: [
                    "common",
                    "draconic",
                    "dwarven",
                    "elven",
                    "fey",
                    "gnomish",
                    "goblin",
                    "halfling",
                    "jotun",
                    "orcish",
                    "undercommon",
                ],
            },
            boosts: {
                "0": { value: ["int"] },
                "1": { value: [] },
                "2": { value: ["str", "dex", "con", "int", "wis", "cha"] },
            },
            description: {
                value:
                    "<p><em>Shisks are secretive mountain-dwellers, bone-feathered humanoids who lurk underground in dark tunnels and caverns. Their fascination with collecting and protecting esoteric knowledge is one of the few things that can persuade them to explore the outside world.</em></p>\n<p><em>@UUID[Compendium.pf2e.journals.JournalEntry.45SK8rdbbxvEHfMn.JournalEntryPage.qsbc1ZLCWzfl1sfZ]{Shisk}</em></p>",
            },
            flaws: { "0": { value: [] } },
            hp: 8,
            items: {},
            languages: { custom: "", value: ["mwangi", "shisk"] },
            publication: {
                license: "OGL",
                remaster: false,
                title: "Pathfinder Lost Omens: The Mwangi Expanse",
            },
            reach: 5,
            rules: [],
            size: "med",
            speed: 25,
            traits: { rarity: "rare", value: ["humanoid", "shisk"] },
            vision: "darkvision",
        },
        type: "ancestry",
    },
    shoony: {
        _id: "q6rsqYARyOGXZA8F",
        img: "systems/pf2e/icons/default-icons/alternatives/ancestries/shoony.webp",
        name: "Shoony",
        system: {
            additionalLanguages: {
                count: 0,
                custom: "",
                value: ["dwarven", "gnomish", "goblin", "halfling", "petran"],
            },
            boosts: {
                "0": { value: ["cha"] },
                "1": { value: ["dex"] },
                "2": { value: ["str", "dex", "con", "int", "wis", "cha"] },
            },
            description: {
                value:
                    "<p><em>Diminutive humanoids who resemble squat, bipedal dogs, shoonies are sometimes mistaken for weak and insular pacifists. However, their sheer perseverance, incredible work ethic, and resourceful use of diplomacy make shoonies far from helpless.</em></p>\n<p><em>@UUID[Compendium.pf2e.journals.JournalEntry.45SK8rdbbxvEHfMn.JournalEntryPage.j2hOTtHcdu2SA8Ha]{Shoony}</em></p>",
            },
            flaws: { "0": { value: ["con"] } },
            hp: 6,
            items: {
                "82kag": {
                    img: "systems/pf2e/icons/features/ancestry/fishseeker-shoony.webp",
                    level: "1",
                    name: "Blunt Snout",
                    uuid: "Compendium.pf2e.ancestryfeatures.Item.Blunt Snout",
                },
            },
            languages: { custom: "", value: ["common", "shoony"] },
            publication: {
                license: "OGL",
                remaster: false,
                title: "Pathfinder #153: Life's Long Shadows",
            },
            reach: 5,
            rules: [],
            size: "sm",
            speed: 25,
            traits: { rarity: "rare", value: ["humanoid", "shoony"] },
            vision: "lowLightVision",
        },
        type: "ancestry",
    },
    skeleton: {
        _id: "58rL5sg2y4arW1i5",
        img: "systems/pf2e/icons/default-icons/alternatives/ancestries/skeleton.svg",
        name: "Skeleton",
        system: {
            additionalLanguages: { count: 0, custom: "", value: [] },
            boosts: {
                "0": { value: ["dex"] },
                "1": { value: ["cha"] },
                "2": { value: ["str", "dex", "con", "int", "wis", "cha"] },
            },
            description: {
                value:
                    "<p><em>Skeletons are considered among the lowest types of undead. They're typically mindless creatures, lacking many of the abilities that make other undead a serious threat. However, the animated bones of dragons, giants, and other great beasts make for dangerous foes. Powerful living creatures can retain some of their might and intellect upon returning as a skeleton. Some necromancers turn their strongest enemies into skeletal undead servants, assuming they can keep control of them.</em></p>\n<p><em>@UUID[Compendium.pf2e.journals.JournalEntry.45SK8rdbbxvEHfMn.JournalEntryPage.EcNSrvwIj22Jxkjz]{Skeleton}</em></p>",
            },
            flaws: { "0": { value: ["int"] } },
            hp: 6,
            items: {},
            languages: { custom: "", value: ["common", "necril"] },
            publication: {
                license: "OGL",
                remaster: false,
                title: "Pathfinder Book of the Dead",
            },
            reach: 5,
            rules: [
                {
                    key: "GrantItem",
                    uuid: "Compendium.pf2e.ancestryfeatures.Item.Basic Undead Benefits",
                },
            ],
            size: "med",
            speed: 25,
            traits: { rarity: "rare", value: ["skeleton", "undead"] },
            vision: "normal",
        },
        type: "ancestry",
    },
    sprite: {
        _id: "TRqoeYfGAFjQbviF",
        img: "systems/pf2e/icons/default-icons/alternatives/ancestries/sprite.svg",
        name: "Sprite",
        system: {
            additionalLanguages: {
                count: 0,
                custom: "",
                value: ["celestial", "draconic", "elven", "gnomish", "goblin", "jotun"],
            },
            boosts: {
                "0": { value: ["dex"] },
                "1": { value: ["int"] },
                "2": { value: ["str", "dex", "con", "int", "wis", "cha"] },
            },
            description: {
                value:
                    "<p><em>Sprites are diminutive, whimsical, and exuberant creatures from the fey realm known as the First World. They love playing pranks, exploring new things, and embracing everything to do with magic.</em></p>\n<p><em>@UUID[Compendium.pf2e.journals.JournalEntry.45SK8rdbbxvEHfMn.JournalEntryPage.rvbMGyBr6y5K7HDP]{Sprite}</em></p>",
            },
            flaws: { "0": { value: ["str"] } },
            hp: 6,
            items: {
                uu6ze: {
                    img: "systems/pf2e/icons/default-icons/feat.svg",
                    level: 1,
                    name: "Magical Strikes",
                    uuid: "Compendium.pf2e.ancestryfeatures.Item.Magical Strikes",
                },
            },
            languages: { custom: "", value: ["common", "fey"] },
            publication: {
                license: "OGL",
                remaster: false,
                title: "Pathfinder Lost Omens: Ancestry Guide",
            },
            reach: 0,
            rules: [],
            size: "tiny",
            speed: 20,
            traits: { rarity: "rare", value: ["fey", "sprite"] },
            vision: "lowLightVision",
        },
        type: "ancestry",
    },
    strix: {
        _id: "GXcC6oVa5quzgNHD",
        img: "systems/pf2e/icons/default-icons/alternatives/ancestries/strix.svg",
        name: "Strix",
        system: {
            additionalLanguages: {
                count: 0,
                custom: "",
                value: ["draconic", "gnomish", "infernal", "jotun"],
            },
            boosts: {
                "0": { value: ["dex"] },
                "1": { value: [] },
                "2": { value: ["str", "dex", "con", "int", "wis", "cha"] },
            },
            description: {
                value:
                    "<p><em>Known as itarii in their own language, strix are reclusive avian humanoids devoted to their homelands and their tribes. They defend their precious communities with broad wingspans and razor talons.</em></p>\n<p><em>@UUID[Compendium.pf2e.journals.JournalEntry.45SK8rdbbxvEHfMn.JournalEntryPage.N8aShsDuf3ur0vZ2]{Strix}</em></p>",
            },
            flaws: { "0": { value: [] } },
            hp: 8,
            items: {
                "64eou": {
                    img: "systems/pf2e/icons/default-icons/feat.svg",
                    level: 1,
                    name: "Wings",
                    uuid: "Compendium.pf2e.ancestryfeatures.Item.Wings",
                },
            },
            languages: { custom: "", value: ["common", "strix"] },
            publication: {
                license: "OGL",
                remaster: false,
                title: "Pathfinder Lost Omens: Ancestry Guide",
            },
            reach: 5,
            rules: [],
            size: "med",
            speed: 25,
            traits: { rarity: "rare", value: ["humanoid", "strix"] },
            vision: "lowLightVision",
        },
        type: "ancestry",
    },
    tengu: {
        _id: "18xDKYPDBLEv2myX",
        img: "systems/pf2e/icons/default-icons/alternatives/ancestries/tengu.svg",
        name: "Tengu",
        system: {
            additionalLanguages: {
                count: 0,
                custom: "",
                value: ["dwarven", "elven", "fey", "gnomish", "goblin", "halfling"],
            },
            boosts: {
                "0": { value: ["dex"] },
                "1": { value: [] },
                "2": { value: ["str", "dex", "con", "int", "wis", "cha"] },
            },
            description: {
                value:
                    "<p><em>Tengus are a gregarious and resourceful people that have spread far and wide from their ancestral home in Tian Xia, collecting and combining whatever innovations and traditions they happen across with those from their own long history.</em></p>\n<p><em>@UUID[Compendium.pf2e.journals.JournalEntry.45SK8rdbbxvEHfMn.JournalEntryPage.YGIwmuVOJI7uNhGM]{Tengu}</em></p>",
            },
            flaws: { "0": { value: [] } },
            hp: 6,
            items: {
                vo9ge: {
                    img: "systems/pf2e/icons/features/ancestry/sharp-beak.webp",
                    level: 0,
                    name: "Sharp Beak",
                    uuid: "Compendium.pf2e.ancestryfeatures.Item.Sharp Beak",
                },
            },
            languages: { custom: "", value: ["common", "tengu"] },
            publication: {
                license: "OGL",
                remaster: false,
                title: "Pathfinder Advanced Player's Guide",
            },
            reach: 5,
            rules: [],
            size: "med",
            speed: 25,
            traits: { rarity: "uncommon", value: ["humanoid", "tengu"] },
            vision: "lowLightVision",
        },
        type: "ancestry",
    },
    vanara: {
        _id: "cLtOGIkuSSa4UDHY",
        img: "systems/pf2e/icons/default-icons/ancestry.svg",
        name: "Vanara",
        system: {
            additionalLanguages: {
                count: 0,
                custom: "",
                value: ["elven", "fey", "gnomish", "goblin", "infernal"],
            },
            boosts: {
                "0": { value: ["dex"] },
                "1": { value: [] },
                "2": { value: ["str", "dex", "con", "int", "wis", "cha"] },
            },
            description: {
                value:
                    "<p>Vanaras are inquisitive and mischievous monkey-like humanoids with short, soft fur, expressive eyes, and long, prehensile tails. Their handlike feet and agile builds serve them well in the jungle realms where most vanaras live.</p>\n<p>@UUID[Compendium.pf2e.journals.JournalEntry.45SK8rdbbxvEHfMn.JournalEntryPage.40koksC576nYV2Tf]{Vanara}</p>",
            },
            flaws: { "0": { value: [] } },
            hp: 6,
            items: {
                "6bSm3": {
                    img: "systems/pf2e/icons/default-icons/feat.svg",
                    level: 0,
                    name: "Prehensile Tail",
                    uuid: "Compendium.pf2e.ancestryfeatures.Item.Prehensile Tail",
                },
            },
            languages: { custom: "", value: ["common", "vanara"] },
            publication: {
                license: "OGL",
                remaster: false,
                title: "Pathfinder Lost Omens: Impossible Lands",
            },
            reach: 5,
            rules: [],
            size: "med",
            speed: 25,
            traits: { rarity: "uncommon", value: ["humanoid", "vanara"] },
            vision: "normal",
        },
        type: "ancestry",
    },
    vishkanya: {
        _id: "u1VJEXsVlmh3Fyx0",
        img: "systems/pf2e/icons/default-icons/ancestry.svg",
        name: "Vishkanya",
        system: {
            additionalLanguages: {
                count: 0,
                custom: "",
                value: [
                    "aklo",
                    "draconic",
                    "elven",
                    "goblin",
                    "thalassic",
                    "undercommon",
                    "vanara",
                ],
            },
            boosts: {
                "0": { value: ["dex"] },
                "1": { value: [] },
                "2": { value: ["str", "dex", "con", "int", "wis", "cha"] },
            },
            description: {
                value:
                    "<p>Vishkanyas are ophidian humanoids who carry potent venom within their blood and saliva. Largely misunderstood due to old tales of their toxicity and natural finesse, vishkanyas work to grow into more than just what stories paint them to be.</p>\n<p>@UUID[Compendium.pf2e.journals.JournalEntry.45SK8rdbbxvEHfMn.JournalEntryPage.1lCAkGgIYYkczZ28]{Vishkanya}</p>",
            },
            flaws: { "0": { value: [] } },
            hp: 8,
            items: {
                "0wY9n": {
                    img: "icons/skills/melee/blade-tip-energy-green.webp",
                    level: 0,
                    name: "Innate Venom",
                    uuid: "Compendium.pf2e.ancestryfeatures.Item.Innate Venom",
                },
            },
            languages: { custom: "", value: ["common", "vishkanyan"] },
            publication: {
                license: "OGL",
                remaster: false,
                title: "Pathfinder Lost Omens: Impossible Lands",
            },
            reach: 5,
            rules: [],
            size: "med",
            speed: 25,
            traits: { rarity: "rare", value: ["humanoid", "vishkanya"] },
            vision: "lowLightVision",
        },
        type: "ancestry",
    },
};
